# Generated by Django 5.0.1 on 2024-05-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproofing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproofing_app.service'),
        ),
    ]
