# Generated by Django 5.0.1 on 2024-05-07 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproofing_app', '0002_remove_inquiry_created_at_inquiry_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
